### ISSUE TITLE
Request on English documentation and different pinyin in font

### ISSUE THREAD

**Issue by NightFurySL2001** [MaruTama/Mengshen-pinyin-font#2]
Is it possible to make English documentation?

Also, how do this font deal with words with different pinyins?

**Comment by MaruTama** [comment]
I am sorry for being late to contact you.

Is this that requested the following documentation?
[HOW_TO_MAKE.md](https://github.com/MaruTama/Mengshen-pinyin-font/blob/master/HOW_TO_MAKE.md)

> "Also, how do this font deal with words with different pinyins?"

What is this mean?  Is "different pinyin" 多音字?

**Comment by NightFurySL2001** [comment]
Thank you for your reply.

Yes, but it would be great if there is English translation for others to use. Documentation usually refers to all documents that are provided for the software, in this case it'll be all the `.md` files in this repo.

> What is this mean? Is "different pinyin" 多音字?
Yes I'm referring to 多音字.

Recently there has been a repo that makes bopomofo with newer OpenType technology, [BPMF IVS](https://github.com/ButTaiwan/bpmfvs). It utilize the IVS (ideographic variant selector) in Unicode to change between different pinyin (eg providing 4 glyphs: zháo zhāo zhe zhuó for 着) and also put the variant glyphs in stylistic set (SS01-04). You can visit that repo and check how it works. BPMF IVS has a pinyin standard in bopomofo, so that all fonts generated with that program can be used interchangably without losing the tonal marks (if using IVD). Is it possible to recreate it in this program? (and maybe use the same pinyin standard, which will make conversion between bopomofo and hanyu pinyin a ton easier by just changing fonts)

**Comment by MaruTama** [comment]
That's a good idea.
We will soon translate all .md files in this repo into English.

This font does not yet support different Pinyin words.
I am thinking of implementing it using the ligature function.
[Implement the ligature #1](https://github.com/MaruTama/Mengshen-pinyin-font/issues/1)

**Comment by NightFurySL2001** [comment]
Thanks. I appreciate the translations :D

Is it possible to generate the different pinyin glyphs with different glyphs name first? The linking can be done later by using glyph names in OpenType e.g. Adobe Feature file (.fea). A simple tutorial for .fea files which can be imported into FontForge is available at [OpenType Cookbook](http://opentypecookbook.com/).

**Comment by MaruTama** [comment]
> Is it possible to generate the different pinyin glyphs with different glyphs name first? 
I don't have the definite answer yet.

Thanks for the link.

**Comment by NightFurySL2001** [comment]
Got it. You're welcome.

I think [HOW_TO_MAKE.md](https://github.com/MaruTama/Mengshen-pinyin-font/blob/master/HOW_TO_MAKE.md) would be a good item to start translating as I guess it provide the steps on how to make the font. Maybe you can make a new HOW_TO_MAKE_EN.md and link them up.

**Comment by NightFurySL2001** [comment]
You're welcome. I'll move the pinyin issue back to #1 .

**Comment by NightFurySL2001** [comment]
(There's still more MD files to translate yet... lol)

**Comment by MaruTama** [comment]
I've translated the document in its entirety.
I will close this issue.

**Comment by NightFurySL2001** [comment]
Thank you!
